version: "3.8"
services:
  
  db_postgres:

    image: postgres:latest
    container_name: crm-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Lấy từ file .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
      - ./init/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d crm_db -U admin"] # crm_db is the name of the database default is postgres
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - localnetwork

networks:
  localnetwork:
    driver: bridge
    external: true