auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s

distributor:
  ring:
    kvstore:
      store: inmemory

query_range:
  align_queries_with_step: true
  max_retries: 5
  # split_queries_by_interval: 15m


schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    # shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: false
  max_cache_freshness_per_query: 10m

# chunk_store_config:
#   max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h # 7 days
