version: "3.8"
services:
  
  rabbit:
    build: .
      # context: .  # Vị trí DockerfileRabbit
      # dockerfile: ./Dockerfile  # Tên Dockerfile bạn đã tạo
    container_name: crm-rabbit
    # image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitadmin
      - RABBITMQ_DEFAULT_PASS=o0qmhvHhFMUVd4L
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - localnetwork

volumes: # Define volumes
  postgres_data: # Name of volume
  log: # Name of volume

networks:
  localnetwork:
    driver: bridge
    external: true