version: '3.8'

services:

  redis:
    build:
      context: .               # Thư mục chứa Dockerfile
      dockerfile: Dockerfile   # Tên Dockerfile (có thể bỏ qua nếu tên là "Dockerfile")
    image: redis:v1
    container_name: vs-redis
    ports:
      - "6379:6379" 
    volumes:
      - ./redis_data:/data
      - ./logs:/var/log/redis
    networks:
      - localnetwork
    restart: always

  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - 5540:5540
    volumes:
      - ./redis_insight_data:/data
    networks:
      - localnetwork
    depends_on:
      - redis


networks:
  localnetwork:
    driver: bridge
    external: true


